

#ifndef H_TYPE_CLASS___
#define H_TYPE_CLASS___

#define LUA_CHRSCR_WC 10
#define MAX_PACKET_SIZE 1024
#define OBJ_OPTION_COUNT 256
#define MAX_CHARACTER_NAME 256
#define MAX_SPELLCARD_NAME 256
#define MAX_STAGE_BULLET_TYPE 256
#define MAX_STAGE_NAME 256
#define MAXLOGINUSER 8
#define MD5_LENGTH 10
#define MAX_GAME_ITEM_TEXT 256
#define MAX_TEAM_COUNT 2
#define CHARA_HIT_RANGE 3
#define CHARA_BODY_RANGE 3
#define D3DDEFAULT_FORMAT D3DFMT_R8G8B8

#endif //H_TYPE_CLASS___