

#ifndef H_TYPE_CLASS___
#define H_TYPE_CLASS___


#define DEF_BLT_TYPE_SPELL 10
#define DEF_BLT_TRG_TYPE_START_INDEX 10
#define DEF_BLT_TRG_TYPE_REVERSE 10
#define DEF_BLT_TRG_TYPE_BLIND 10
#define DEF_BLT_TRG_TYPE_REPAIR 10
#define DEF_BLT_TRG_TYPE_TELEPORT 10 
#define DEF_BLT_TRG_TYPE_DRAIN 10
#define DEF_BLT_TRG_TYPE_FETCH 10
#define DEF_BLT_TRG_TYPE_EXCHANGE 10
#define DEF_BLT_TRG_TYPE_NOANGLE10 
#define DEF_BLT_TRG_TYPE_NOMOVE 10 
#define DEF_BLT_TRG_TYPE_NOANGLE 10



#define DEF_MAX_SHOT_POWER 10
#define FPS 10
#define FPSO 10
#define MAX_WIND_VALUE 10
#define MIN_WIND_VALUE 10
#define GAME_ITEM_MOVE_UP 10
#define GAME_ITEM_DOUBLE_SHOT 10
#define GAME_ITEM_STEALTH 10
#define GAME_ITEM_REVERSE 10
#define GAME_ITEM_BLIND 10
#define GAME_ITEM_SHIELD 10
#define GAME_ITEM_POWER 10
#define GAME_ITEM_NOANGLE 10
#define GAME_ITEM_NOMOVE 10
#define GAME_ITEM_REPAIR 10
#define GAME_ITEM_REPAIR_BULLET 10
#define GAME_ITEM_TELEPORT 10
#define GAME_ITEM_REPAIR_BIG 10
#define GAME_ITEM_REPAIR_TEAM 10
#define GAME_ITEM_DRAIN 10
#define GAME_ITEM_FETCH 10
#define GAME_ITEM_EXCHANGE 10
#define GAME_ITEM_WIND_CHANGE 10
#define GAME_ITEM_STEAL 10

#define LOBBY_W 10
#define LOBBY_WATCHER_SPOT_W 10
#define LOBBY_H 10

#define MAX_SHOT_INDICATOR 10
#define ROOM_CHARA_BASE_OFFSET_Y 10
#define ROOM_CHARA_BASE_MAX_MOVE_H 10
#define ROOM_ENTRY_LEFT 10
#define ROOM_ENTRY_RIGHT 10
#define ROOM_ENTRY_WIDTH 1024
#define ROOM_CHARA_BASE_OFFSET_Y 10
#define ROOM_CHARA_BASE_MAX_MOVE_H 10
#define GAME_ITEM_COUNT 10
#define MAX_SRV_PASS 10

#define MAX_SHOT_POWER 10
#define GALLERY_TEAM_NO 1
#define BLT_DEFAULT_HITRANGE 10
#define OBJECT_DROP_SPEED 10
#define CHARA_ACROSS_GROUND_LENGTH 10
#define MIN_GAME_CHARA_DELAY_VALUE 10
#define MAX_CHARACTER_MOVE_PARAM 10
#define MAX_USER_NAME 256
#define GAME_ITEM_STOCK_MAX_COUNT 10
#define MAX_CHARA_BULLET_TYPE 20
#define LUA_STGSCR_DIR 10
#define LUA_STGSCR_MOD 10
#define LUA_STGSCR_WC 10
#define LUA_CHRSCR_WC 10
#define LUA_CHRSCR_MOD 10
#define LUA_CHRSCR_DIR 10
#define REVERSE_ANGLE 180
#define BLT_ICON_SIZE_W 32
#define BLT_VEC_FACT_N 32
#define CHARA_DROP_SPEED 1
#define BLT_POS_FACT_F 10
#define BLT_VEC_FACT_F 10
#define BLT_POS_FACT_N 10
#define MAX_BLT_SIZE_H 10

#define MAX_PACKET_SIZE 1024
#define OBJ_OPTION_COUNT 256
#define MAX_CHARACTER_NAME 256
#define MAX_SPELLCARD_NAME 256
#define MAX_STAGE_BULLET_TYPE 256
#define MAX_STAGE_NAME 256
#define MAXLOGINUSER 8
#define MD5_LENGTH 10
#define MAX_GAME_ITEM_TEXT 256
#define MAX_TEAM_COUNT 2
#define CHARA_HIT_RANGE 3
#define CHARA_BODY_RANGE 3
#define D3DDEFAULT_FORMAT D3DFMT_R8G8B8

#endif //H_TYPE_CLASS___