

#ifndef H_TYPE_CLASS___
#define H_TYPE_CLASS___

#define MAX_USER_NAME 256
#define GAME_ITEM_STOCK_MAX_COUNT 10
#define MAX_CHARA_BULLET_TYPE 20
#define LUA_STGSCR_DIR 10
#define LUA_STGSCR_MOD 10
#define LUA_STGSCR_WC 10
#define LUA_CHRSCR_WC 10
#define LUA_CHRSCR_MOD 10
#define LUA_CHRSCR_DIR 10
#define BLT_ICON_SIZE_W 10
#define REVERSE_ANGLE 180
#define BLT_ICON_SIZE_W 32
#define BLT_VEC_FACT_N 32
#define CHARA_DROP_SPEED 1
#define BLT_POS_FACT_F 10
#define BLT_VEC_FACT_F 10
#define BLT_POS_FACT_N 10
#define BLT_VEC_FACT_N 10
#define MAX_BLT_SIZE_H 10

#define MAX_PACKET_SIZE 1024
#define OBJ_OPTION_COUNT 256
#define MAX_CHARACTER_NAME 256
#define MAX_SPELLCARD_NAME 256
#define MAX_STAGE_BULLET_TYPE 256
#define MAX_STAGE_NAME 256
#define MAXLOGINUSER 8
#define MD5_LENGTH 10
#define MAX_GAME_ITEM_TEXT 256
#define MAX_TEAM_COUNT 2
#define CHARA_HIT_RANGE 3
#define CHARA_BODY_RANGE 3
#define D3DDEFAULT_FORMAT D3DFMT_R8G8B8

#endif //H_TYPE_CLASS___